name: Projects

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        project:
          - PlatformTest:
            repository: "Jason2866/platform-test"
            folder: "src"
            config_dir: "src"
            env_name: "esp32-s3"
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        
